"""Boundary layer for using CQDAGPCFG as a serial oracle and block provider."""

from .block_graph import (
    ROOT_NODE_ID,
    BlockNodeDescriptor,
    CQDAGBlockGraphAdapter,
    CQDAGRecordSource,
    CQDAGSourceReclaimStats,
    CQDAGStructureRecordSource,
    slot_entropy,
    slot_entropy_bound,
)
from .paged_source import (
    PagedCQDAGModelClient,
    PagedCQDAGRecordSource,
    PagedCQDAGStructureRecordSource,
    PagedModelStats,
    PagedPcfgModel,
    PagedSlotTable,
    build_paged_model,
)
from .node_source import (
    CQDAGNodeSourceConfig,
    build_cqdag_node_source,
    resolve_cqdag_model_path,
)
from .node_service import (
    AnnotatedCQDAGPCFGNode,
    CQDAGCandidate,
    CQDAGPCFGFramework,
    CQDAGPCFGNodeContext,
    CQDAGPCFGNode,
    CqdagNodeAgentServiceConfig,
    cqdagpcfg,
    cqdagpcfg_consumer,
    cqdagpcfg_generator,
    cqdagpcfg_node_agent,
    cqdagpcfg_remote,
    pcfg,
)
from .tracker_service import (
    AnnotatedCQDAGPCFGTracker,
    CQDAGPCFGBatchRetryEvent,
    CQDAGPCFGCheckpointEvent,
    CQDAGPCFGMemorySnapshot,
    CQDAGPCFGNodeEvent,
    CQDAGPCFGRoleChangeEvent,
    CQDAGPCFGTrackerError,
    CQDAGPCFGTrackerJob,
    CQDAGPCFGTrackerSummary,
    CQDAGPCFGTracker,
    CqdagTrackerServiceConfig,
    StreamingRecordBatchPublisher,
    cqdagpcfg_tracker,
)
from .serial_oracle import SerialCQDAGOracle, SerialOracleResult

__all__ = [
    "BlockNodeDescriptor",
    "AnnotatedCQDAGPCFGNode",
    "AnnotatedCQDAGPCFGTracker",
    "CQDAGCandidate",
    "CQDAGPCFGFramework",
    "CQDAGNodeSourceConfig",
    "CQDAGPCFGNodeContext",
    "CQDAGPCFGNode",
    "CQDAGPCFGBatchRetryEvent",
    "CQDAGPCFGCheckpointEvent",
    "CQDAGPCFGMemorySnapshot",
    "CQDAGPCFGNodeEvent",
    "CQDAGPCFGRoleChangeEvent",
    "CQDAGPCFGTrackerError",
    "CQDAGPCFGTrackerJob",
    "CQDAGPCFGTrackerSummary",
    "CQDAGPCFGTracker",
    "CqdagNodeAgentServiceConfig",
    "CqdagTrackerServiceConfig",
    "CQDAGBlockGraphAdapter",
    "CQDAGRecordSource",
    "CQDAGSourceReclaimStats",
    "CQDAGStructureRecordSource",
    "PagedCQDAGModelClient",
    "PagedCQDAGRecordSource",
    "PagedCQDAGStructureRecordSource",
    "PagedModelStats",
    "PagedPcfgModel",
    "PagedSlotTable",
    "ROOT_NODE_ID",
    "SerialCQDAGOracle",
    "SerialOracleResult",
    "StreamingRecordBatchPublisher",
    "build_paged_model",
    "build_cqdag_node_source",
    "cqdagpcfg",
    "cqdagpcfg_consumer",
    "cqdagpcfg_generator",
    "cqdagpcfg_node_agent",
    "cqdagpcfg_remote",
    "cqdagpcfg_tracker",
    "pcfg",
    "resolve_cqdag_model_path",
    "slot_entropy",
    "slot_entropy_bound",
]
